# Generated by Django 6.0.5 on 2026-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_accent',
            field=models.CharField(default='#00d4ff', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp_points',
            field=models.IntegerField(default=0),
        ),
    ]
