# Generated by Django 6.0.5 on 2026-05-27 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo_icon', models.CharField(default='fas fa-building', max_length=100)),
                ('color', models.CharField(default='#00d4ff', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('hiring_status', models.CharField(choices=[('hiring', 'Actively Hiring'), ('limited', 'Limited Openings'), ('closed', 'Closed'), ('upcoming', 'Opening Soon')], default='hiring', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='medium', max_length=20)),
                ('salary_min', models.IntegerField(default=0, help_text='Annual salary in USD (thousands)')),
                ('salary_max', models.IntegerField(default=0)),
                ('open_positions', models.IntegerField(default=0)),
                ('interview_rounds', models.IntegerField(default=4)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('hiring_deadline', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('in_progress', 'In Progress'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30)),
                ('cover_note', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.company')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('online_test', 'Online Test'), ('technical_1', 'Technical Round 1'), ('technical_2', 'Technical Round 2'), ('hr', 'HR Round'), ('managerial', 'Managerial Round'), ('final', 'Final Round')], default='technical_1', max_length=20)),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('max_candidates', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='companies.company')),
            ],
            options={
                'ordering': ['date', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='InterviewBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('confirmation_code', models.CharField(blank=True, max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='companies.application')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='companies.interviewslot')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
    ]
