# Generated by Django 6.0.5 on 2026-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_tips',
            field=models.TextField(blank=True, help_text='Pipe-separated AI preparation tips'),
        ),
        migrations.AddField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True, help_text='Official careers/jobs page URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='culture_tags',
            field=models.TextField(blank=True, help_text='Comma-separated culture keywords'),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_process',
            field=models.TextField(blank=True, help_text='Pipe-separated interview round descriptions'),
        ),
    ]
