# Generated by Django 6.0.5 on 2026-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['difficulty', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty_filter',
            field=models.CharField(choices=[('all', 'All Levels'), ('easy', 'Beginner'), ('medium', 'Intermediate'), ('hard', 'Advanced')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Beginner'), ('medium', 'Intermediate'), ('hard', 'Advanced')], default='medium', max_length=10),
        ),
    ]
